apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-pod-reader
subjects:
- kind: User
  name: jhonSRE 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cr-pod-reader
  apiGroup: rbac.authorization.k8s.io