apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "First Deployment"  
  name: deployment-test
  labels:
    app: front
spec: 
  replicas: 5
  selector:
    matchLabels:
      app: pod-label
  template:
    metadata:
      labels:
        app: pod-label
    spec:
      containers:
          - name: nginx
            image: nginx:alpine
            ports:
            - containerPort: 110