apiVersion: v1
kind: Namespace
metadata:
    name: prod
    labels:
      name: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: prod
  name: sa-read-pods
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "prod deployment start"  
  name: deployment-prod
  namespace: prod
  labels:
    app: front
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      serviceAccountName: sa-read-pods
      containers:
      - name: nginx
        image: nginx:alpine